### ISSUE TITLE
Unexpected token with jspm 0.17.0-beta.7 / systemjs-hot-reloader 0.5.6

### ISSUE THREAD

**Issue by jingignoli** [capaj/systemjs-hot-reloader#59]
Hi,

Since I'am using jspm 0.17.0-beta.7 and systemjs-hot-reloader 0.5.6, i've got this error:

`SyntaxError:` http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/babel-helpers/createClass.js: Unexpected token (17:2)
  15 |     return Constructor;
  16 |   };
> 17 | }();
	Error loading http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/babel-helpers/createClass.js as "http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/babel-helpers/createClass.js" from http://localhost:3000/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.6/hot-reloader.js
    at b.h.raise (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:27415)
    at b.i.unexpected (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:17:21408)
    at b.k.parseParenAndDistinguishExpression (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:17999)
    at b.k.parseExprAtom (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:15430)
    at b.k.parseExprSubscripts (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:11114)
    at b.k.parseMaybeUnary (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:10732)
    at b.k.parseExprOps (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:9385)
    at b.k.parseMaybeConditional (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:9034)
    at b.k.parseMaybeAssign (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:8322)
    at b.k.parseExpression (http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/systemjs-babel-browser.js:16:7742)`

Any help is welcome :-)

Julie.

**Comment by capaj** [comment]
@jingignoli have you followed the guide: http://jspm.io/0.17-beta-guide/hot-reloading.html ?

**Comment by jingignoli** [comment]
Yes of course but the import caused the previous 'syntax error'
`import 'systemjs-hot-reloader/default-listener.js'`

**Comment by guybedford** [comment]
@jingignoli try updating the Babel plugin to version 0.0.5.

**Comment by jingignoli** [comment]
Yes ! It works, thank you.
